// Code generated by ent, DO NOT EDIT.

package uservoucher

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ChungKiet/cake-interview/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldLTE(FieldID, id))
}

// VoucherCampaignID applies equality check predicate on the "voucher_campaign_id" field. It's identical to VoucherCampaignIDEQ.
func VoucherCampaignID(v int64) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldEQ(FieldVoucherCampaignID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldEQ(FieldUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldEQ(FieldUpdatedAt, v))
}

// VoucherCampaignIDEQ applies the EQ predicate on the "voucher_campaign_id" field.
func VoucherCampaignIDEQ(v int64) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldEQ(FieldVoucherCampaignID, v))
}

// VoucherCampaignIDNEQ applies the NEQ predicate on the "voucher_campaign_id" field.
func VoucherCampaignIDNEQ(v int64) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldNEQ(FieldVoucherCampaignID, v))
}

// VoucherCampaignIDIn applies the In predicate on the "voucher_campaign_id" field.
func VoucherCampaignIDIn(vs ...int64) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldIn(FieldVoucherCampaignID, vs...))
}

// VoucherCampaignIDNotIn applies the NotIn predicate on the "voucher_campaign_id" field.
func VoucherCampaignIDNotIn(vs ...int64) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldNotIn(FieldVoucherCampaignID, vs...))
}

// VoucherCampaignIDGT applies the GT predicate on the "voucher_campaign_id" field.
func VoucherCampaignIDGT(v int64) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldGT(FieldVoucherCampaignID, v))
}

// VoucherCampaignIDGTE applies the GTE predicate on the "voucher_campaign_id" field.
func VoucherCampaignIDGTE(v int64) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldGTE(FieldVoucherCampaignID, v))
}

// VoucherCampaignIDLT applies the LT predicate on the "voucher_campaign_id" field.
func VoucherCampaignIDLT(v int64) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldLT(FieldVoucherCampaignID, v))
}

// VoucherCampaignIDLTE applies the LTE predicate on the "voucher_campaign_id" field.
func VoucherCampaignIDLTE(v int64) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldLTE(FieldVoucherCampaignID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldContainsFold(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserVoucher {
	return predicate.UserVoucher(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserVoucher) predicate.UserVoucher {
	return predicate.UserVoucher(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserVoucher) predicate.UserVoucher {
	return predicate.UserVoucher(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserVoucher) predicate.UserVoucher {
	return predicate.UserVoucher(sql.NotPredicates(p))
}
