// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CampaignsColumns holds the columns for the "campaigns" table.
	CampaignsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "current_slot", Type: field.TypeInt64},
		{Name: "start_day", Type: field.TypeTime},
		{Name: "end_day", Type: field.TypeTime},
		{Name: "total_slot", Type: field.TypeInt64},
		{Name: "is_full", Type: field.TypeBool},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CampaignsTable holds the schema information for the "campaigns" table.
	CampaignsTable = &schema.Table{
		Name:       "campaigns",
		Columns:    CampaignsColumns,
		PrimaryKey: []*schema.Column{CampaignsColumns[0]},
	}
	// CardsColumns holds the columns for the "cards" table.
	CardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "value", Type: field.TypeFloat64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CardsTable holds the schema information for the "cards" table.
	CardsTable = &schema.Table{
		Name:       "cards",
		Columns:    CardsColumns,
		PrimaryKey: []*schema.Column{CardsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString},
		{Name: "account", Type: field.TypeString},
		{Name: "full_name", Type: field.TypeString},
		{Name: "phone_numer", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "user_name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "birthday", Type: field.TypeTime},
		{Name: "latest_login", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserBalancesColumns holds the columns for the "user_balances" table.
	UserBalancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeString},
		{Name: "balance", Type: field.TypeFloat64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserBalancesTable holds the schema information for the "user_balances" table.
	UserBalancesTable = &schema.Table{
		Name:       "user_balances",
		Columns:    UserBalancesColumns,
		PrimaryKey: []*schema.Column{UserBalancesColumns[0]},
	}
	// UserVouchersColumns holds the columns for the "user_vouchers" table.
	UserVouchersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "voucher_campaign_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserVouchersTable holds the schema information for the "user_vouchers" table.
	UserVouchersTable = &schema.Table{
		Name:       "user_vouchers",
		Columns:    UserVouchersColumns,
		PrimaryKey: []*schema.Column{UserVouchersColumns[0]},
	}
	// VouchersColumns holds the columns for the "vouchers" table.
	VouchersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "value", Type: field.TypeFloat64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// VouchersTable holds the schema information for the "vouchers" table.
	VouchersTable = &schema.Table{
		Name:       "vouchers",
		Columns:    VouchersColumns,
		PrimaryKey: []*schema.Column{VouchersColumns[0]},
	}
	// VoucherCampaignsColumns holds the columns for the "voucher_campaigns" table.
	VoucherCampaignsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "campaign_id", Type: field.TypeInt64},
		{Name: "voucher_id", Type: field.TypeInt64},
		{Name: "start_day", Type: field.TypeTime},
		{Name: "valid_to", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// VoucherCampaignsTable holds the schema information for the "voucher_campaigns" table.
	VoucherCampaignsTable = &schema.Table{
		Name:       "voucher_campaigns",
		Columns:    VoucherCampaignsColumns,
		PrimaryKey: []*schema.Column{VoucherCampaignsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CampaignsTable,
		CardsTable,
		UsersTable,
		UserBalancesTable,
		UserVouchersTable,
		VouchersTable,
		VoucherCampaignsTable,
	}
)

func init() {
}
