// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ChungKiet/cake-interview/ent/campaign"
)

// CampaignCreate is the builder for creating a Campaign entity.
type CampaignCreate struct {
	config
	mutation *CampaignMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (cc *CampaignCreate) SetName(s string) *CampaignCreate {
	cc.mutation.SetName(s)
	return cc
}

// SetCurrentSlot sets the "current_slot" field.
func (cc *CampaignCreate) SetCurrentSlot(i int64) *CampaignCreate {
	cc.mutation.SetCurrentSlot(i)
	return cc
}

// SetStartDay sets the "start_day" field.
func (cc *CampaignCreate) SetStartDay(t time.Time) *CampaignCreate {
	cc.mutation.SetStartDay(t)
	return cc
}

// SetEndDay sets the "end_day" field.
func (cc *CampaignCreate) SetEndDay(t time.Time) *CampaignCreate {
	cc.mutation.SetEndDay(t)
	return cc
}

// SetTotalSlot sets the "total_slot" field.
func (cc *CampaignCreate) SetTotalSlot(i int64) *CampaignCreate {
	cc.mutation.SetTotalSlot(i)
	return cc
}

// SetIsFull sets the "is_full" field.
func (cc *CampaignCreate) SetIsFull(b bool) *CampaignCreate {
	cc.mutation.SetIsFull(b)
	return cc
}

// SetCreatedAt sets the "created_at" field.
func (cc *CampaignCreate) SetCreatedAt(t time.Time) *CampaignCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CampaignCreate) SetNillableCreatedAt(t *time.Time) *CampaignCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *CampaignCreate) SetUpdatedAt(t time.Time) *CampaignCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *CampaignCreate) SetNillableUpdatedAt(t *time.Time) *CampaignCreate {
	if t != nil {
		cc.SetUpdatedAt(*t)
	}
	return cc
}

// Mutation returns the CampaignMutation object of the builder.
func (cc *CampaignCreate) Mutation() *CampaignMutation {
	return cc.mutation
}

// Save creates the Campaign in the database.
func (cc *CampaignCreate) Save(ctx context.Context) (*Campaign, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CampaignCreate) SaveX(ctx context.Context) *Campaign {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CampaignCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CampaignCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CampaignCreate) defaults() {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := campaign.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		v := campaign.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CampaignCreate) check() error {
	if _, ok := cc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Campaign.name"`)}
	}
	if _, ok := cc.mutation.CurrentSlot(); !ok {
		return &ValidationError{Name: "current_slot", err: errors.New(`ent: missing required field "Campaign.current_slot"`)}
	}
	if _, ok := cc.mutation.StartDay(); !ok {
		return &ValidationError{Name: "start_day", err: errors.New(`ent: missing required field "Campaign.start_day"`)}
	}
	if _, ok := cc.mutation.EndDay(); !ok {
		return &ValidationError{Name: "end_day", err: errors.New(`ent: missing required field "Campaign.end_day"`)}
	}
	if _, ok := cc.mutation.TotalSlot(); !ok {
		return &ValidationError{Name: "total_slot", err: errors.New(`ent: missing required field "Campaign.total_slot"`)}
	}
	if _, ok := cc.mutation.IsFull(); !ok {
		return &ValidationError{Name: "is_full", err: errors.New(`ent: missing required field "Campaign.is_full"`)}
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Campaign.created_at"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Campaign.updated_at"`)}
	}
	return nil
}

func (cc *CampaignCreate) sqlSave(ctx context.Context) (*Campaign, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CampaignCreate) createSpec() (*Campaign, *sqlgraph.CreateSpec) {
	var (
		_node = &Campaign{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(campaign.Table, sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.Name(); ok {
		_spec.SetField(campaign.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := cc.mutation.CurrentSlot(); ok {
		_spec.SetField(campaign.FieldCurrentSlot, field.TypeInt64, value)
		_node.CurrentSlot = value
	}
	if value, ok := cc.mutation.StartDay(); ok {
		_spec.SetField(campaign.FieldStartDay, field.TypeTime, value)
		_node.StartDay = value
	}
	if value, ok := cc.mutation.EndDay(); ok {
		_spec.SetField(campaign.FieldEndDay, field.TypeTime, value)
		_node.EndDay = value
	}
	if value, ok := cc.mutation.TotalSlot(); ok {
		_spec.SetField(campaign.FieldTotalSlot, field.TypeInt64, value)
		_node.TotalSlot = value
	}
	if value, ok := cc.mutation.IsFull(); ok {
		_spec.SetField(campaign.FieldIsFull, field.TypeBool, value)
		_node.IsFull = value
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(campaign.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(campaign.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CampaignCreateBulk is the builder for creating many Campaign entities in bulk.
type CampaignCreateBulk struct {
	config
	err      error
	builders []*CampaignCreate
}

// Save creates the Campaign entities in the database.
func (ccb *CampaignCreateBulk) Save(ctx context.Context) ([]*Campaign, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Campaign, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CampaignMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CampaignCreateBulk) SaveX(ctx context.Context) []*Campaign {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CampaignCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CampaignCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
