// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ChungKiet/cake-interview/ent/campaign"
	"github.com/ChungKiet/cake-interview/ent/card"
	"github.com/ChungKiet/cake-interview/ent/schema"
	"github.com/ChungKiet/cake-interview/ent/user"
	"github.com/ChungKiet/cake-interview/ent/userbalance"
	"github.com/ChungKiet/cake-interview/ent/uservoucher"
	"github.com/ChungKiet/cake-interview/ent/voucher"
	"github.com/ChungKiet/cake-interview/ent/vouchercampaign"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	campaignFields := schema.Campaign{}.Fields()
	_ = campaignFields
	// campaignDescCreatedAt is the schema descriptor for created_at field.
	campaignDescCreatedAt := campaignFields[6].Descriptor()
	// campaign.DefaultCreatedAt holds the default value on creation for the created_at field.
	campaign.DefaultCreatedAt = campaignDescCreatedAt.Default.(func() time.Time)
	// campaignDescUpdatedAt is the schema descriptor for updated_at field.
	campaignDescUpdatedAt := campaignFields[7].Descriptor()
	// campaign.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	campaign.DefaultUpdatedAt = campaignDescUpdatedAt.Default.(func() time.Time)
	// campaign.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	campaign.UpdateDefaultUpdatedAt = campaignDescUpdatedAt.UpdateDefault.(func() time.Time)
	cardFields := schema.Card{}.Fields()
	_ = cardFields
	// cardDescCreatedAt is the schema descriptor for created_at field.
	cardDescCreatedAt := cardFields[3].Descriptor()
	// card.DefaultCreatedAt holds the default value on creation for the created_at field.
	card.DefaultCreatedAt = cardDescCreatedAt.Default.(func() time.Time)
	// cardDescUpdatedAt is the schema descriptor for updated_at field.
	cardDescUpdatedAt := cardFields[4].Descriptor()
	// card.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	card.DefaultUpdatedAt = cardDescUpdatedAt.Default.(func() time.Time)
	// card.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	card.UpdateDefaultUpdatedAt = cardDescUpdatedAt.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescFullName is the schema descriptor for full_name field.
	userDescFullName := userFields[2].Descriptor()
	// user.FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	user.FullNameValidator = userDescFullName.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[6].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	userbalanceFields := schema.UserBalance{}.Fields()
	_ = userbalanceFields
	// userbalanceDescCreatedAt is the schema descriptor for created_at field.
	userbalanceDescCreatedAt := userbalanceFields[2].Descriptor()
	// userbalance.DefaultCreatedAt holds the default value on creation for the created_at field.
	userbalance.DefaultCreatedAt = userbalanceDescCreatedAt.Default.(func() time.Time)
	// userbalanceDescUpdatedAt is the schema descriptor for updated_at field.
	userbalanceDescUpdatedAt := userbalanceFields[3].Descriptor()
	// userbalance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userbalance.DefaultUpdatedAt = userbalanceDescUpdatedAt.Default.(func() time.Time)
	// userbalance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userbalance.UpdateDefaultUpdatedAt = userbalanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	uservoucherFields := schema.UserVoucher{}.Fields()
	_ = uservoucherFields
	// uservoucherDescCreatedAt is the schema descriptor for created_at field.
	uservoucherDescCreatedAt := uservoucherFields[2].Descriptor()
	// uservoucher.DefaultCreatedAt holds the default value on creation for the created_at field.
	uservoucher.DefaultCreatedAt = uservoucherDescCreatedAt.Default.(func() time.Time)
	// uservoucherDescUpdatedAt is the schema descriptor for updated_at field.
	uservoucherDescUpdatedAt := uservoucherFields[3].Descriptor()
	// uservoucher.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	uservoucher.DefaultUpdatedAt = uservoucherDescUpdatedAt.Default.(func() time.Time)
	// uservoucher.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	uservoucher.UpdateDefaultUpdatedAt = uservoucherDescUpdatedAt.UpdateDefault.(func() time.Time)
	voucherFields := schema.Voucher{}.Fields()
	_ = voucherFields
	// voucherDescCreatedAt is the schema descriptor for created_at field.
	voucherDescCreatedAt := voucherFields[3].Descriptor()
	// voucher.DefaultCreatedAt holds the default value on creation for the created_at field.
	voucher.DefaultCreatedAt = voucherDescCreatedAt.Default.(func() time.Time)
	// voucherDescUpdatedAt is the schema descriptor for updated_at field.
	voucherDescUpdatedAt := voucherFields[4].Descriptor()
	// voucher.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	voucher.DefaultUpdatedAt = voucherDescUpdatedAt.Default.(func() time.Time)
	// voucher.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	voucher.UpdateDefaultUpdatedAt = voucherDescUpdatedAt.UpdateDefault.(func() time.Time)
	vouchercampaignFields := schema.VoucherCampaign{}.Fields()
	_ = vouchercampaignFields
	// vouchercampaignDescCreatedAt is the schema descriptor for created_at field.
	vouchercampaignDescCreatedAt := vouchercampaignFields[4].Descriptor()
	// vouchercampaign.DefaultCreatedAt holds the default value on creation for the created_at field.
	vouchercampaign.DefaultCreatedAt = vouchercampaignDescCreatedAt.Default.(func() time.Time)
	// vouchercampaignDescUpdatedAt is the schema descriptor for updated_at field.
	vouchercampaignDescUpdatedAt := vouchercampaignFields[5].Descriptor()
	// vouchercampaign.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vouchercampaign.DefaultUpdatedAt = vouchercampaignDescUpdatedAt.Default.(func() time.Time)
	// vouchercampaign.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vouchercampaign.UpdateDefaultUpdatedAt = vouchercampaignDescUpdatedAt.UpdateDefault.(func() time.Time)
}
