// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ChungKiet/cake-interview/ent/predicate"
	"github.com/ChungKiet/cake-interview/ent/uservoucher"
)

// UserVoucherUpdate is the builder for updating UserVoucher entities.
type UserVoucherUpdate struct {
	config
	hooks    []Hook
	mutation *UserVoucherMutation
}

// Where appends a list predicates to the UserVoucherUpdate builder.
func (uvu *UserVoucherUpdate) Where(ps ...predicate.UserVoucher) *UserVoucherUpdate {
	uvu.mutation.Where(ps...)
	return uvu
}

// SetVoucherCampaignID sets the "voucher_campaign_id" field.
func (uvu *UserVoucherUpdate) SetVoucherCampaignID(i int64) *UserVoucherUpdate {
	uvu.mutation.ResetVoucherCampaignID()
	uvu.mutation.SetVoucherCampaignID(i)
	return uvu
}

// AddVoucherCampaignID adds i to the "voucher_campaign_id" field.
func (uvu *UserVoucherUpdate) AddVoucherCampaignID(i int64) *UserVoucherUpdate {
	uvu.mutation.AddVoucherCampaignID(i)
	return uvu
}

// SetUserID sets the "user_id" field.
func (uvu *UserVoucherUpdate) SetUserID(s string) *UserVoucherUpdate {
	uvu.mutation.SetUserID(s)
	return uvu
}

// SetUpdatedAt sets the "updated_at" field.
func (uvu *UserVoucherUpdate) SetUpdatedAt(t time.Time) *UserVoucherUpdate {
	uvu.mutation.SetUpdatedAt(t)
	return uvu
}

// Mutation returns the UserVoucherMutation object of the builder.
func (uvu *UserVoucherUpdate) Mutation() *UserVoucherMutation {
	return uvu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uvu *UserVoucherUpdate) Save(ctx context.Context) (int, error) {
	uvu.defaults()
	return withHooks(ctx, uvu.sqlSave, uvu.mutation, uvu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uvu *UserVoucherUpdate) SaveX(ctx context.Context) int {
	affected, err := uvu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uvu *UserVoucherUpdate) Exec(ctx context.Context) error {
	_, err := uvu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uvu *UserVoucherUpdate) ExecX(ctx context.Context) {
	if err := uvu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uvu *UserVoucherUpdate) defaults() {
	if _, ok := uvu.mutation.UpdatedAt(); !ok {
		v := uservoucher.UpdateDefaultUpdatedAt()
		uvu.mutation.SetUpdatedAt(v)
	}
}

func (uvu *UserVoucherUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(uservoucher.Table, uservoucher.Columns, sqlgraph.NewFieldSpec(uservoucher.FieldID, field.TypeInt))
	if ps := uvu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uvu.mutation.VoucherCampaignID(); ok {
		_spec.SetField(uservoucher.FieldVoucherCampaignID, field.TypeInt64, value)
	}
	if value, ok := uvu.mutation.AddedVoucherCampaignID(); ok {
		_spec.AddField(uservoucher.FieldVoucherCampaignID, field.TypeInt64, value)
	}
	if value, ok := uvu.mutation.UserID(); ok {
		_spec.SetField(uservoucher.FieldUserID, field.TypeString, value)
	}
	if value, ok := uvu.mutation.UpdatedAt(); ok {
		_spec.SetField(uservoucher.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uvu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uservoucher.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uvu.mutation.done = true
	return n, nil
}

// UserVoucherUpdateOne is the builder for updating a single UserVoucher entity.
type UserVoucherUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserVoucherMutation
}

// SetVoucherCampaignID sets the "voucher_campaign_id" field.
func (uvuo *UserVoucherUpdateOne) SetVoucherCampaignID(i int64) *UserVoucherUpdateOne {
	uvuo.mutation.ResetVoucherCampaignID()
	uvuo.mutation.SetVoucherCampaignID(i)
	return uvuo
}

// AddVoucherCampaignID adds i to the "voucher_campaign_id" field.
func (uvuo *UserVoucherUpdateOne) AddVoucherCampaignID(i int64) *UserVoucherUpdateOne {
	uvuo.mutation.AddVoucherCampaignID(i)
	return uvuo
}

// SetUserID sets the "user_id" field.
func (uvuo *UserVoucherUpdateOne) SetUserID(s string) *UserVoucherUpdateOne {
	uvuo.mutation.SetUserID(s)
	return uvuo
}

// SetUpdatedAt sets the "updated_at" field.
func (uvuo *UserVoucherUpdateOne) SetUpdatedAt(t time.Time) *UserVoucherUpdateOne {
	uvuo.mutation.SetUpdatedAt(t)
	return uvuo
}

// Mutation returns the UserVoucherMutation object of the builder.
func (uvuo *UserVoucherUpdateOne) Mutation() *UserVoucherMutation {
	return uvuo.mutation
}

// Where appends a list predicates to the UserVoucherUpdate builder.
func (uvuo *UserVoucherUpdateOne) Where(ps ...predicate.UserVoucher) *UserVoucherUpdateOne {
	uvuo.mutation.Where(ps...)
	return uvuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uvuo *UserVoucherUpdateOne) Select(field string, fields ...string) *UserVoucherUpdateOne {
	uvuo.fields = append([]string{field}, fields...)
	return uvuo
}

// Save executes the query and returns the updated UserVoucher entity.
func (uvuo *UserVoucherUpdateOne) Save(ctx context.Context) (*UserVoucher, error) {
	uvuo.defaults()
	return withHooks(ctx, uvuo.sqlSave, uvuo.mutation, uvuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uvuo *UserVoucherUpdateOne) SaveX(ctx context.Context) *UserVoucher {
	node, err := uvuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uvuo *UserVoucherUpdateOne) Exec(ctx context.Context) error {
	_, err := uvuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uvuo *UserVoucherUpdateOne) ExecX(ctx context.Context) {
	if err := uvuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uvuo *UserVoucherUpdateOne) defaults() {
	if _, ok := uvuo.mutation.UpdatedAt(); !ok {
		v := uservoucher.UpdateDefaultUpdatedAt()
		uvuo.mutation.SetUpdatedAt(v)
	}
}

func (uvuo *UserVoucherUpdateOne) sqlSave(ctx context.Context) (_node *UserVoucher, err error) {
	_spec := sqlgraph.NewUpdateSpec(uservoucher.Table, uservoucher.Columns, sqlgraph.NewFieldSpec(uservoucher.FieldID, field.TypeInt))
	id, ok := uvuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserVoucher.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uvuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uservoucher.FieldID)
		for _, f := range fields {
			if !uservoucher.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != uservoucher.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uvuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uvuo.mutation.VoucherCampaignID(); ok {
		_spec.SetField(uservoucher.FieldVoucherCampaignID, field.TypeInt64, value)
	}
	if value, ok := uvuo.mutation.AddedVoucherCampaignID(); ok {
		_spec.AddField(uservoucher.FieldVoucherCampaignID, field.TypeInt64, value)
	}
	if value, ok := uvuo.mutation.UserID(); ok {
		_spec.SetField(uservoucher.FieldUserID, field.TypeString, value)
	}
	if value, ok := uvuo.mutation.UpdatedAt(); ok {
		_spec.SetField(uservoucher.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserVoucher{config: uvuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uvuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uservoucher.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uvuo.mutation.done = true
	return _node, nil
}
