// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ChungKiet/cake-interview/ent/userbalance"
)

// UserBalance is the model entity for the UserBalance schema.
type UserBalance struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance float64 `json:"balance,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserBalance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userbalance.FieldBalance:
			values[i] = new(sql.NullFloat64)
		case userbalance.FieldID:
			values[i] = new(sql.NullInt64)
		case userbalance.FieldUserID:
			values[i] = new(sql.NullString)
		case userbalance.FieldCreatedAt, userbalance.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserBalance fields.
func (ub *UserBalance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userbalance.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ub.ID = int(value.Int64)
		case userbalance.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ub.UserID = value.String
			}
		case userbalance.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				ub.Balance = value.Float64
			}
		case userbalance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ub.CreatedAt = value.Time
			}
		case userbalance.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ub.UpdatedAt = value.Time
			}
		default:
			ub.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserBalance.
// This includes values selected through modifiers, order, etc.
func (ub *UserBalance) Value(name string) (ent.Value, error) {
	return ub.selectValues.Get(name)
}

// Update returns a builder for updating this UserBalance.
// Note that you need to call UserBalance.Unwrap() before calling this method if this UserBalance
// was returned from a transaction, and the transaction was committed or rolled back.
func (ub *UserBalance) Update() *UserBalanceUpdateOne {
	return NewUserBalanceClient(ub.config).UpdateOne(ub)
}

// Unwrap unwraps the UserBalance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ub *UserBalance) Unwrap() *UserBalance {
	_tx, ok := ub.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserBalance is not a transactional entity")
	}
	ub.config.driver = _tx.drv
	return ub
}

// String implements the fmt.Stringer.
func (ub *UserBalance) String() string {
	var builder strings.Builder
	builder.WriteString("UserBalance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ub.ID))
	builder.WriteString("user_id=")
	builder.WriteString(ub.UserID)
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", ub.Balance))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ub.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ub.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserBalances is a parsable slice of UserBalance.
type UserBalances []*UserBalance
