// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ChungKiet/cake-interview/ent/predicate"
	"github.com/ChungKiet/cake-interview/ent/userbalance"
)

// UserBalanceUpdate is the builder for updating UserBalance entities.
type UserBalanceUpdate struct {
	config
	hooks    []Hook
	mutation *UserBalanceMutation
}

// Where appends a list predicates to the UserBalanceUpdate builder.
func (ubu *UserBalanceUpdate) Where(ps ...predicate.UserBalance) *UserBalanceUpdate {
	ubu.mutation.Where(ps...)
	return ubu
}

// SetUserID sets the "user_id" field.
func (ubu *UserBalanceUpdate) SetUserID(s string) *UserBalanceUpdate {
	ubu.mutation.SetUserID(s)
	return ubu
}

// SetBalance sets the "balance" field.
func (ubu *UserBalanceUpdate) SetBalance(f float64) *UserBalanceUpdate {
	ubu.mutation.ResetBalance()
	ubu.mutation.SetBalance(f)
	return ubu
}

// AddBalance adds f to the "balance" field.
func (ubu *UserBalanceUpdate) AddBalance(f float64) *UserBalanceUpdate {
	ubu.mutation.AddBalance(f)
	return ubu
}

// SetUpdatedAt sets the "updated_at" field.
func (ubu *UserBalanceUpdate) SetUpdatedAt(t time.Time) *UserBalanceUpdate {
	ubu.mutation.SetUpdatedAt(t)
	return ubu
}

// Mutation returns the UserBalanceMutation object of the builder.
func (ubu *UserBalanceUpdate) Mutation() *UserBalanceMutation {
	return ubu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ubu *UserBalanceUpdate) Save(ctx context.Context) (int, error) {
	ubu.defaults()
	return withHooks(ctx, ubu.sqlSave, ubu.mutation, ubu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ubu *UserBalanceUpdate) SaveX(ctx context.Context) int {
	affected, err := ubu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ubu *UserBalanceUpdate) Exec(ctx context.Context) error {
	_, err := ubu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ubu *UserBalanceUpdate) ExecX(ctx context.Context) {
	if err := ubu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ubu *UserBalanceUpdate) defaults() {
	if _, ok := ubu.mutation.UpdatedAt(); !ok {
		v := userbalance.UpdateDefaultUpdatedAt()
		ubu.mutation.SetUpdatedAt(v)
	}
}

func (ubu *UserBalanceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userbalance.Table, userbalance.Columns, sqlgraph.NewFieldSpec(userbalance.FieldID, field.TypeInt))
	if ps := ubu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ubu.mutation.UserID(); ok {
		_spec.SetField(userbalance.FieldUserID, field.TypeString, value)
	}
	if value, ok := ubu.mutation.Balance(); ok {
		_spec.SetField(userbalance.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := ubu.mutation.AddedBalance(); ok {
		_spec.AddField(userbalance.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := ubu.mutation.UpdatedAt(); ok {
		_spec.SetField(userbalance.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ubu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbalance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ubu.mutation.done = true
	return n, nil
}

// UserBalanceUpdateOne is the builder for updating a single UserBalance entity.
type UserBalanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserBalanceMutation
}

// SetUserID sets the "user_id" field.
func (ubuo *UserBalanceUpdateOne) SetUserID(s string) *UserBalanceUpdateOne {
	ubuo.mutation.SetUserID(s)
	return ubuo
}

// SetBalance sets the "balance" field.
func (ubuo *UserBalanceUpdateOne) SetBalance(f float64) *UserBalanceUpdateOne {
	ubuo.mutation.ResetBalance()
	ubuo.mutation.SetBalance(f)
	return ubuo
}

// AddBalance adds f to the "balance" field.
func (ubuo *UserBalanceUpdateOne) AddBalance(f float64) *UserBalanceUpdateOne {
	ubuo.mutation.AddBalance(f)
	return ubuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ubuo *UserBalanceUpdateOne) SetUpdatedAt(t time.Time) *UserBalanceUpdateOne {
	ubuo.mutation.SetUpdatedAt(t)
	return ubuo
}

// Mutation returns the UserBalanceMutation object of the builder.
func (ubuo *UserBalanceUpdateOne) Mutation() *UserBalanceMutation {
	return ubuo.mutation
}

// Where appends a list predicates to the UserBalanceUpdate builder.
func (ubuo *UserBalanceUpdateOne) Where(ps ...predicate.UserBalance) *UserBalanceUpdateOne {
	ubuo.mutation.Where(ps...)
	return ubuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ubuo *UserBalanceUpdateOne) Select(field string, fields ...string) *UserBalanceUpdateOne {
	ubuo.fields = append([]string{field}, fields...)
	return ubuo
}

// Save executes the query and returns the updated UserBalance entity.
func (ubuo *UserBalanceUpdateOne) Save(ctx context.Context) (*UserBalance, error) {
	ubuo.defaults()
	return withHooks(ctx, ubuo.sqlSave, ubuo.mutation, ubuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ubuo *UserBalanceUpdateOne) SaveX(ctx context.Context) *UserBalance {
	node, err := ubuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ubuo *UserBalanceUpdateOne) Exec(ctx context.Context) error {
	_, err := ubuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ubuo *UserBalanceUpdateOne) ExecX(ctx context.Context) {
	if err := ubuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ubuo *UserBalanceUpdateOne) defaults() {
	if _, ok := ubuo.mutation.UpdatedAt(); !ok {
		v := userbalance.UpdateDefaultUpdatedAt()
		ubuo.mutation.SetUpdatedAt(v)
	}
}

func (ubuo *UserBalanceUpdateOne) sqlSave(ctx context.Context) (_node *UserBalance, err error) {
	_spec := sqlgraph.NewUpdateSpec(userbalance.Table, userbalance.Columns, sqlgraph.NewFieldSpec(userbalance.FieldID, field.TypeInt))
	id, ok := ubuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserBalance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ubuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userbalance.FieldID)
		for _, f := range fields {
			if !userbalance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userbalance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ubuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ubuo.mutation.UserID(); ok {
		_spec.SetField(userbalance.FieldUserID, field.TypeString, value)
	}
	if value, ok := ubuo.mutation.Balance(); ok {
		_spec.SetField(userbalance.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := ubuo.mutation.AddedBalance(); ok {
		_spec.AddField(userbalance.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := ubuo.mutation.UpdatedAt(); ok {
		_spec.SetField(userbalance.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserBalance{config: ubuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ubuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbalance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ubuo.mutation.done = true
	return _node, nil
}
