// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ChungKiet/cake-interview/ent/predicate"
	"github.com/ChungKiet/cake-interview/ent/vouchercampaign"
)

// VoucherCampaignQuery is the builder for querying VoucherCampaign entities.
type VoucherCampaignQuery struct {
	config
	ctx        *QueryContext
	order      []vouchercampaign.OrderOption
	inters     []Interceptor
	predicates []predicate.VoucherCampaign
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VoucherCampaignQuery builder.
func (vcq *VoucherCampaignQuery) Where(ps ...predicate.VoucherCampaign) *VoucherCampaignQuery {
	vcq.predicates = append(vcq.predicates, ps...)
	return vcq
}

// Limit the number of records to be returned by this query.
func (vcq *VoucherCampaignQuery) Limit(limit int) *VoucherCampaignQuery {
	vcq.ctx.Limit = &limit
	return vcq
}

// Offset to start from.
func (vcq *VoucherCampaignQuery) Offset(offset int) *VoucherCampaignQuery {
	vcq.ctx.Offset = &offset
	return vcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vcq *VoucherCampaignQuery) Unique(unique bool) *VoucherCampaignQuery {
	vcq.ctx.Unique = &unique
	return vcq
}

// Order specifies how the records should be ordered.
func (vcq *VoucherCampaignQuery) Order(o ...vouchercampaign.OrderOption) *VoucherCampaignQuery {
	vcq.order = append(vcq.order, o...)
	return vcq
}

// First returns the first VoucherCampaign entity from the query.
// Returns a *NotFoundError when no VoucherCampaign was found.
func (vcq *VoucherCampaignQuery) First(ctx context.Context) (*VoucherCampaign, error) {
	nodes, err := vcq.Limit(1).All(setContextOp(ctx, vcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{vouchercampaign.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vcq *VoucherCampaignQuery) FirstX(ctx context.Context) *VoucherCampaign {
	node, err := vcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VoucherCampaign ID from the query.
// Returns a *NotFoundError when no VoucherCampaign ID was found.
func (vcq *VoucherCampaignQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vcq.Limit(1).IDs(setContextOp(ctx, vcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{vouchercampaign.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vcq *VoucherCampaignQuery) FirstIDX(ctx context.Context) int {
	id, err := vcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VoucherCampaign entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VoucherCampaign entity is found.
// Returns a *NotFoundError when no VoucherCampaign entities are found.
func (vcq *VoucherCampaignQuery) Only(ctx context.Context) (*VoucherCampaign, error) {
	nodes, err := vcq.Limit(2).All(setContextOp(ctx, vcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{vouchercampaign.Label}
	default:
		return nil, &NotSingularError{vouchercampaign.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vcq *VoucherCampaignQuery) OnlyX(ctx context.Context) *VoucherCampaign {
	node, err := vcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VoucherCampaign ID in the query.
// Returns a *NotSingularError when more than one VoucherCampaign ID is found.
// Returns a *NotFoundError when no entities are found.
func (vcq *VoucherCampaignQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vcq.Limit(2).IDs(setContextOp(ctx, vcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{vouchercampaign.Label}
	default:
		err = &NotSingularError{vouchercampaign.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vcq *VoucherCampaignQuery) OnlyIDX(ctx context.Context) int {
	id, err := vcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VoucherCampaigns.
func (vcq *VoucherCampaignQuery) All(ctx context.Context) ([]*VoucherCampaign, error) {
	ctx = setContextOp(ctx, vcq.ctx, "All")
	if err := vcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VoucherCampaign, *VoucherCampaignQuery]()
	return withInterceptors[[]*VoucherCampaign](ctx, vcq, qr, vcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (vcq *VoucherCampaignQuery) AllX(ctx context.Context) []*VoucherCampaign {
	nodes, err := vcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VoucherCampaign IDs.
func (vcq *VoucherCampaignQuery) IDs(ctx context.Context) (ids []int, err error) {
	if vcq.ctx.Unique == nil && vcq.path != nil {
		vcq.Unique(true)
	}
	ctx = setContextOp(ctx, vcq.ctx, "IDs")
	if err = vcq.Select(vouchercampaign.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vcq *VoucherCampaignQuery) IDsX(ctx context.Context) []int {
	ids, err := vcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vcq *VoucherCampaignQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, vcq.ctx, "Count")
	if err := vcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, vcq, querierCount[*VoucherCampaignQuery](), vcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (vcq *VoucherCampaignQuery) CountX(ctx context.Context) int {
	count, err := vcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vcq *VoucherCampaignQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, vcq.ctx, "Exist")
	switch _, err := vcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (vcq *VoucherCampaignQuery) ExistX(ctx context.Context) bool {
	exist, err := vcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VoucherCampaignQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vcq *VoucherCampaignQuery) Clone() *VoucherCampaignQuery {
	if vcq == nil {
		return nil
	}
	return &VoucherCampaignQuery{
		config:     vcq.config,
		ctx:        vcq.ctx.Clone(),
		order:      append([]vouchercampaign.OrderOption{}, vcq.order...),
		inters:     append([]Interceptor{}, vcq.inters...),
		predicates: append([]predicate.VoucherCampaign{}, vcq.predicates...),
		// clone intermediate query.
		sql:  vcq.sql.Clone(),
		path: vcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CampaignID int64 `json:"campaign_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VoucherCampaign.Query().
//		GroupBy(vouchercampaign.FieldCampaignID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (vcq *VoucherCampaignQuery) GroupBy(field string, fields ...string) *VoucherCampaignGroupBy {
	vcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VoucherCampaignGroupBy{build: vcq}
	grbuild.flds = &vcq.ctx.Fields
	grbuild.label = vouchercampaign.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CampaignID int64 `json:"campaign_id,omitempty"`
//	}
//
//	client.VoucherCampaign.Query().
//		Select(vouchercampaign.FieldCampaignID).
//		Scan(ctx, &v)
func (vcq *VoucherCampaignQuery) Select(fields ...string) *VoucherCampaignSelect {
	vcq.ctx.Fields = append(vcq.ctx.Fields, fields...)
	sbuild := &VoucherCampaignSelect{VoucherCampaignQuery: vcq}
	sbuild.label = vouchercampaign.Label
	sbuild.flds, sbuild.scan = &vcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VoucherCampaignSelect configured with the given aggregations.
func (vcq *VoucherCampaignQuery) Aggregate(fns ...AggregateFunc) *VoucherCampaignSelect {
	return vcq.Select().Aggregate(fns...)
}

func (vcq *VoucherCampaignQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range vcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, vcq); err != nil {
				return err
			}
		}
	}
	for _, f := range vcq.ctx.Fields {
		if !vouchercampaign.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vcq.path != nil {
		prev, err := vcq.path(ctx)
		if err != nil {
			return err
		}
		vcq.sql = prev
	}
	return nil
}

func (vcq *VoucherCampaignQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VoucherCampaign, error) {
	var (
		nodes = []*VoucherCampaign{}
		_spec = vcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VoucherCampaign).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VoucherCampaign{config: vcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, vcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (vcq *VoucherCampaignQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vcq.querySpec()
	_spec.Node.Columns = vcq.ctx.Fields
	if len(vcq.ctx.Fields) > 0 {
		_spec.Unique = vcq.ctx.Unique != nil && *vcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, vcq.driver, _spec)
}

func (vcq *VoucherCampaignQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(vouchercampaign.Table, vouchercampaign.Columns, sqlgraph.NewFieldSpec(vouchercampaign.FieldID, field.TypeInt))
	_spec.From = vcq.sql
	if unique := vcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if vcq.path != nil {
		_spec.Unique = true
	}
	if fields := vcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vouchercampaign.FieldID)
		for i := range fields {
			if fields[i] != vouchercampaign.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vcq *VoucherCampaignQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vcq.driver.Dialect())
	t1 := builder.Table(vouchercampaign.Table)
	columns := vcq.ctx.Fields
	if len(columns) == 0 {
		columns = vouchercampaign.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vcq.sql != nil {
		selector = vcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if vcq.ctx.Unique != nil && *vcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range vcq.predicates {
		p(selector)
	}
	for _, p := range vcq.order {
		p(selector)
	}
	if offset := vcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VoucherCampaignGroupBy is the group-by builder for VoucherCampaign entities.
type VoucherCampaignGroupBy struct {
	selector
	build *VoucherCampaignQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vcgb *VoucherCampaignGroupBy) Aggregate(fns ...AggregateFunc) *VoucherCampaignGroupBy {
	vcgb.fns = append(vcgb.fns, fns...)
	return vcgb
}

// Scan applies the selector query and scans the result into the given value.
func (vcgb *VoucherCampaignGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vcgb.build.ctx, "GroupBy")
	if err := vcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoucherCampaignQuery, *VoucherCampaignGroupBy](ctx, vcgb.build, vcgb, vcgb.build.inters, v)
}

func (vcgb *VoucherCampaignGroupBy) sqlScan(ctx context.Context, root *VoucherCampaignQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(vcgb.fns))
	for _, fn := range vcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*vcgb.flds)+len(vcgb.fns))
		for _, f := range *vcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*vcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VoucherCampaignSelect is the builder for selecting fields of VoucherCampaign entities.
type VoucherCampaignSelect struct {
	*VoucherCampaignQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (vcs *VoucherCampaignSelect) Aggregate(fns ...AggregateFunc) *VoucherCampaignSelect {
	vcs.fns = append(vcs.fns, fns...)
	return vcs
}

// Scan applies the selector query and scans the result into the given value.
func (vcs *VoucherCampaignSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, vcs.ctx, "Select")
	if err := vcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VoucherCampaignQuery, *VoucherCampaignSelect](ctx, vcs.VoucherCampaignQuery, vcs, vcs.inters, v)
}

func (vcs *VoucherCampaignSelect) sqlScan(ctx context.Context, root *VoucherCampaignQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(vcs.fns))
	for _, fn := range vcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*vcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
