// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Campaign is the predicate function for campaign builders.
type Campaign func(*sql.Selector)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserBalance is the predicate function for userbalance builders.
type UserBalance func(*sql.Selector)

// UserVoucher is the predicate function for uservoucher builders.
type UserVoucher func(*sql.Selector)

// Voucher is the predicate function for voucher builders.
type Voucher func(*sql.Selector)

// VoucherCampaign is the predicate function for vouchercampaign builders.
type VoucherCampaign func(*sql.Selector)
